# Generated by Django 5.0.6 on 2024-09-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('available_countries', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pictures', models.ImageField(upload_to='products/')),
                ('barcode_info', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('votes_by_community', models.IntegerField(default=0)),
                ('comments_by_community', models.TextField(blank=True)),
                ('source_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
