from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet, IngredientViewSet

# Create one router instance
router = DefaultRouter()

# Register both Product and Ingredient viewsets
router.register(r'products', ProductViewSet, basename='product')
router.register(r'ingredients', IngredientViewSet, basename='ingredient')

# Include all the URLs generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
                        